name: Build Only

on:
    workflow_dispatch:
    push:
        branches: ['latest']
    pull_request:
        branches: ['main', 'latest']

jobs:
    Linux:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Secret Scanning
              uses: trufflesecurity/trufflehog@main
              with:
                  extra_args: --results=verified,unknown

            - name: Setup node env
              uses: actions/setup-node@v4
              with:
                  node-version: latest
                  check-latest: true

            - name: Install dependencies
              run: npm ci --quiet

            - name: Run prepare
              run: npm run prepare

            - name: Run linter
              run: npm run lint

            - name: Run build
              run: npm run build
