name: Package NPM Dependencies

on:
    workflow_dispatch:

jobs:
    Windows:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Get Short Commit Hash
              id: commit_hash
              run: echo "short_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Setup node env
              uses: actions/setup-node@v4
              with:
                  node-version: latest
                  check-latest: true

            - name: Install dependencies
              run: npm ci --quiet

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: NPM_Deps_${{ steps.commit_hash.outputs.short_hash }}
                  path: node_modules
                  retention-days: 7
